### ISSUE TITLE
Add rubocop defaults

### ISSUE THREAD

**Issue by westoque** [narralabs/thomas#13]
The default rubocop cops are too restrictive for narra. Change the settings such that:

```yaml
require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 20
```

We'll add more here once we discover more cops we need to loosen up.
